### ISSUE TITLE
Make Glados less annoying

### ISSUE THREAD

**Issue by filthy-hipster** [londonhackspace/Doorbot#27]
Hi all,

Had idea and spoke to few people about it and they like the idea.

Basically have a check on the card sounds, as we now have the yard and people will be coming in and out to get stuff. Can we add a line of code that when you tap in it checks if the audio has been played in the last hour, if it has been played, do not play again, if not, play audio.

Regards
Chris
Hipster

**Comment by marksteward** [comment]
Possible solution from Cadmus:
```
import subprocess
 
# Working Sox Pipe
# time sox /media/library/Music/The_Terrible_Secret_Of_Space.mp3 -t wav - trim 0 00:05 | --norm sox -t wav - -t wav - | aplay
 
trunc_p = subprocess.Popen(["sox", "/media/library/Music/The_Terrible_Secret_Of_Space.mp3", "-t", "wav", "-", "trim", "0", "00:05"], stdout=subprocess.PIPE)
norm_p = subprocess.Popen(["sox", "--norm", "-t", "wav", "-", "-t", "wav", "-"], stdin=trunc_p.stdout, stdout=subprocess.PIPE)
play_p = subprocess.Popen(["aplay"], stdin=norm_p.stdout)
 
play_p.wait()
```

**Comment by marksteward** [comment]
Also apparently just a single sox command works: "sox --norm file.foo -t wav - trim 0 00:05 | mplay"

**Comment by marksteward** [comment]
Looks like we also need remote volume control, as the required volume varies a lot between a Tuesday evening and a quiet afternoon.
