### ISSUE TITLE
Glados queues unplayable sounds

### ISSUE THREAD

**Issue by marksteward** [londonhackspace/Doorbot#8]
Babbage was down for a while: when it came back up, Bell played all the greetings in the intervening time in one go.  That's gotta be annoying.

**Comment by zymurgic** [comment]
Nowadays we recommend sound files are web hosted, and the script will try to fetch the URL and play it.

**Comment by zymurgic** [comment]
No longer NFS mounts files, so this wouldn't be an issue.
